name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dependencies
        run: go mod download

      - name: lint
      - runs-on: ubuntu-latest
      - steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
          with:
            go-version: stable
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v8
          with:
            version: v2.1

      - name: Run tests
        run: go test ./... -v

      - name: Upload coverage report
        if: success()
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

  deploy:
    needs: lint-and-test
    if: success() && github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
