name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Download dependencies
        run: go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=3m

      - name: Run tests
        run: go test ./... -v

      - name: Upload coverage report
        if: success()
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

  deploy:
    needs: lint-and-test
    if: success() && github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
